In [2]:
from football_prediction.data_loader import load_and_merge_data
from football_prediction.preprocessing import clean_match_data
from football_prediction.features import create_features

In [3]:
data = load_and_merge_data("../data/raw")
data = clean_match_data(data)
data = create_features(data)

data.head()

,date,home_team,away_team,home_goals,away_goals,result,home_avg_goals_scored_last_5,home_avg_goals_conceded_last_5,home_avg_points_last_5,away_avg_goals_scored_last_5,away_avg_goals_conceded_last_5,away_avg_points_last_5
0,2020-09-12,Fulham,Arsenal,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-09-12,Crystal Palace,Southampton,1,0,H,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-09-12,Liverpool,Leeds,4,3,H,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-09-12,West Ham,Newcastle,0,2,A,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-09-13,West Brom,Leicester,0,3,A,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1900 entries, 0 to 1899
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   date                            1900 non-null   datetime64[us]
 1   home_team                       1900 non-null   str
 2   away_team                       1900 non-null   str
 3   home_goals                      1900 non-null   int64
 4   away_goals                      1900 non-null   int64
 5   result                          1900 non-null   str
 6   home_avg_goals_scored_last_5    1885 non-null   float64
 7   home_avg_goals_conceded_last_5  1885 non-null   float64
 8   home_avg_points_last_5          1885 non-null   float64
 9   away_avg_goals_scored_last_5    1888 non-null   float64
 10  away_avg_goals_conceded_last_5  1888 non-null   float64
 11  away_avg_points_last_5          1888 non-null   float64
dtypes: datetime64[us](1), float64(6), int64(2), str(3)
memory usage: 178.3 KB

In [5]:
data[[
    "home_team",
    "away_team",
    "home_avg_goals_scored_last_5",
    "away_avg_goals_scored_last_5",
    "home_avg_points_last_5",
    "away_avg_points_last_5"
]].head(10)

,home_team,away_team,home_avg_goals_scored_last_5,away_avg_goals_scored_last_5,home_avg_points_last_5,away_avg_points_last_5
0,Fulham,Arsenal,NaN,NaN,NaN,NaN
1,Crystal Palace,Southampton,NaN,NaN,NaN,NaN
2,Liverpool,Leeds,NaN,NaN,NaN,NaN
3,West Ham,Newcastle,NaN,NaN,NaN,NaN
4,West Brom,Leicester,NaN,NaN,NaN,NaN
5,Tottenham,Everton,NaN,NaN,NaN,NaN
6,Brighton,Chelsea,NaN,NaN,NaN,NaN
7,Sheffield United,Wolves,NaN,NaN,NaN,NaN
8,Arsenal,West Ham,3.0,0.0,3.0,0.0
9,Man United,Crystal Palace,NaN,1.0,NaN,3.0