In [37]:
import importlib
import football_prediction.features as f

importlib.reload(f)

In [38]:
from football_prediction.data_loader import load_and_merge_data
from football_prediction.preprocessing import clean_match_data
from football_prediction.features import create_features

In [39]:
data = load_and_merge_data("../data/raw")
data = clean_match_data(data)
data = create_features(data)

In [40]:
data.head()

,date,home_team,away_team,home_goals,away_goals,result,home_avg_goals_scored_last_3,home_avg_goals_conceded_last_3,home_avg_points_last_3,home_avg_goal_diff_last_3,...,away_avg_goals_scored_last_10,away_avg_goals_conceded_last_10,away_avg_points_last_10,away_avg_goal_diff_last_10,avg_home_goals_scored_last_5,avg_home_goals_conceded_last_5,avg_home_points_last_5,avg_away_goals_scored_last_5,avg_away_goals_conceded_last_5,avg_away_points_last_5
0,2020-09-12,Fulham,Arsenal,0,3,A,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-09-12,Crystal Palace,Southampton,1,0,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-09-12,Liverpool,Leeds,4,3,H,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-09-12,West Ham,Newcastle,0,2,A,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-09-13,West Brom,Leicester,0,3,A,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1900 entries, 0 to 1899
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   date                             1900 non-null   datetime64[us]
 1   home_team                        1900 non-null   str
 2   away_team                        1900 non-null   str
 3   home_goals                       1900 non-null   int64
 4   away_goals                       1900 non-null   int64
 5   result                           1900 non-null   str
 6   home_avg_goals_scored_last_3     1885 non-null   float64
 7   home_avg_goals_conceded_last_3   1885 non-null   float64
 8   home_avg_points_last_3           1885 non-null   float64
 9   home_avg_goal_diff_last_3        1885 non-null   float64
 10  home_avg_goals_scored_last_5     1885 non-null   float64
 11  home_avg_goals_conceded_last_5   1885 non-null   float64
 12  home_avg_points_last_5           1885 non-null   float64
 13  home_avg_goal_diff_last_5        1885 non-null   float64
 14  home_avg_goals_scored_last_10    1885 non-null   float64
 15  home_avg_goals_conceded_last_10  1885 non-null   float64
 16  home_avg_points_last_10          1885 non-null   float64
 17  home_avg_goal_diff_last_10       1885 non-null   float64
 18  away_avg_goals_scored_last_3     1888 non-null   float64
 19  away_avg_goals_conceded_last_3   1888 non-null   float64
 20  away_avg_points_last_3           1888 non-null   float64
 21  away_avg_goal_diff_last_3        1888 non-null   float64
 22  away_avg_goals_scored_last_5     1888 non-null   float64
 23  away_avg_goals_conceded_last_5   1888 non-null   float64
 24  away_avg_points_last_5           1888 non-null   float64
 25  away_avg_goal_diff_last_5        1888 non-null   float64
 26  away_avg_goals_scored_last_10    1888 non-null   float64
 27  away_avg_goals_conceded_last_10  1888 non-null   float64
 28  away_avg_points_last_10          1888 non-null   float64
 29  away_avg_goal_diff_last_10       1888 non-null   float64
 30  avg_home_goals_scored_last_5     1873 non-null   float64
 31  avg_home_goals_conceded_last_5   1873 non-null   float64
 32  avg_home_points_last_5           1873 non-null   float64
 33  avg_away_goals_scored_last_5     1873 non-null   float64
 34  avg_away_goals_conceded_last_5   1873 non-null   float64
 35  avg_away_points_last_5           1873 non-null   float64
dtypes: datetime64[us](1), float64(30), int64(2), str(3)
memory usage: 534.5 KB

In [42]:
data.columns

Index(['date', 'home_team', 'away_team', 'home_goals', 'away_goals', 'result',
       'home_avg_goals_scored_last_3', 'home_avg_goals_conceded_last_3',
       'home_avg_points_last_3', 'home_avg_goal_diff_last_3',
       'home_avg_goals_scored_last_5', 'home_avg_goals_conceded_last_5',
       'home_avg_points_last_5', 'home_avg_goal_diff_last_5',
       'home_avg_goals_scored_last_10', 'home_avg_goals_conceded_last_10',
       'home_avg_points_last_10', 'home_avg_goal_diff_last_10',
       'away_avg_goals_scored_last_3', 'away_avg_goals_conceded_last_3',
       'away_avg_points_last_3', 'away_avg_goal_diff_last_3',
       'away_avg_goals_scored_last_5', 'away_avg_goals_conceded_last_5',
       'away_avg_points_last_5', 'away_avg_goal_diff_last_5',
       'away_avg_goals_scored_last_10', 'away_avg_goals_conceded_last_10',
       'away_avg_points_last_10', 'away_avg_goal_diff_last_10',
       'avg_home_goals_scored_last_5', 'avg_home_goals_conceded_last_5',
       'avg_home_points_last_5', 'avg_away_goals_scored_last_5',
       'avg_away_goals_conceded_last_5', 'avg_away_points_last_5'],
      dtype='str')

In [43]:
feature_cols = [
    "home_avg_goals_scored_last_3",
    "home_avg_goals_scored_last_5",
    "home_avg_goals_scored_last_10",
    "away_avg_goals_scored_last_3",
    "away_avg_goals_scored_last_5",
    "away_avg_goals_scored_last_10",
    "home_avg_points_last_3",
    "home_avg_points_last_5",
    "home_avg_points_last_10",
    "away_avg_points_last_3",
    "away_avg_points_last_5",
    "away_avg_points_last_10",
    "home_avg_goal_diff_last_3",
    "home_avg_goal_diff_last_5",
    "home_avg_goal_diff_last_10",
    "away_avg_goal_diff_last_3",
    "away_avg_goal_diff_last_5",
    "away_avg_goal_diff_last_10",
]

data[feature_cols].head(10)

,home_avg_goals_scored_last_3,home_avg_goals_scored_last_5,home_avg_goals_scored_last_10,away_avg_goals_scored_last_3,away_avg_goals_scored_last_5,away_avg_goals_scored_last_10,home_avg_points_last_3,home_avg_points_last_5,home_avg_points_last_10,away_avg_points_last_3,away_avg_points_last_5,away_avg_points_last_10,home_avg_goal_diff_last_3,home_avg_goal_diff_last_5,home_avg_goal_diff_last_10,away_avg_goal_diff_last_3,away_avg_goal_diff_last_5,away_avg_goal_diff_last_10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,3.0,3.0,3.0,0.0,0.0,0.0,3.0,3.0,3.0,0.0,0.0,0.0,3.0,3.0,3.0,-2.0,-2.0,-2.0
9,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,3.0,3.0,3.0,NaN,NaN,NaN,1.0,1.0,1.0

In [44]:
sorted(data.columns.tolist())

['avg_away_goals_conceded_last_5',
 'avg_away_goals_scored_last_5',
 'avg_away_points_last_5',
 'avg_home_goals_conceded_last_5',
 'avg_home_goals_scored_last_5',
 'avg_home_points_last_5',
 'away_avg_goal_diff_last_10',
 'away_avg_goal_diff_last_3',
 'away_avg_goal_diff_last_5',
 'away_avg_goals_conceded_last_10',
 'away_avg_goals_conceded_last_3',
 'away_avg_goals_conceded_last_5',
 'away_avg_goals_scored_last_10',
 'away_avg_goals_scored_last_3',
 'away_avg_goals_scored_last_5',
 'away_avg_points_last_10',
 'away_avg_points_last_3',
 'away_avg_points_last_5',
 'away_goals',
 'away_team',
 'date',
 'home_avg_goal_diff_last_10',
 'home_avg_goal_diff_last_3',
 'home_avg_goal_diff_last_5',
 'home_avg_goals_conceded_last_10',
 'home_avg_goals_conceded_last_3',
 'home_avg_goals_conceded_last_5',
 'home_avg_goals_scored_last_10',
 'home_avg_goals_scored_last_3',
 'home_avg_goals_scored_last_5',
 'home_avg_points_last_10',
 'home_avg_points_last_3',
 'home_avg_points_last_5',
 'home_goals',
 'home_team',
 'result']

In [45]:
data[[
    "home_team",
    "away_team",
    "home_avg_goals_scored_last_5",
    "away_avg_goals_scored_last_5",
    "home_avg_points_last_5",
    "away_avg_points_last_5"
]].isna().sum()

home_team                        0
away_team                        0
home_avg_goals_scored_last_5    15
away_avg_goals_scored_last_5    12
home_avg_points_last_5          15
away_avg_points_last_5          12
dtype: int64

In [46]:
feature_cols = [
    "home_avg_goals_scored_last_5",
    "away_avg_goals_scored_last_5",
    "home_avg_points_last_5",
    "away_avg_points_last_5"
]

data = data.dropna(subset=feature_cols)

In [47]:
data[feature_cols].isna().sum()

home_avg_goals_scored_last_5    0
away_avg_goals_scored_last_5    0
home_avg_points_last_5          0
away_avg_points_last_5          0
dtype: int64

In [48]:
def create_features(df: pd.DataFrame) -> pd.DataFrame:
    df = prepare_features_data(df)
    team_df = create_team_match_table(df)
    team_df = add_rolling_team_features(team_df, windows=[3, 5, 10])
    df = merge_team_features_into_matches(df, team_df, windows=[3, 5, 10])
    df = add_home_away_form_features(df, windows=[5])
    return df

In [51]:
home_away_feature_cols = [
    "avg_home_goals_scored_last_5",
    "avg_home_goals_conceded_last_5",
    "avg_home_points_last_5",
    "avg_away_goals_scored_last_5",
    "avg_away_goals_conceded_last_5",
    "avg_away_points_last_5",
]

data[home_away_feature_cols].head(10)

,avg_home_goals_scored_last_5,avg_home_goals_conceded_last_5,avg_home_points_last_5,avg_away_goals_scored_last_5,avg_away_goals_conceded_last_5,avg_away_points_last_5
8,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
18,0.0,3.0,0.0,3.0,1.0,3.0
19,NaN,NaN,NaN,0.0,1.0,0.0
20,1.0,3.0,0.0,NaN,NaN,NaN
21,1.0,0.0,3.0,1.0,0.0,3.0

In [52]:
data[home_away_feature_cols].isna().sum()

avg_home_goals_scored_last_5      10
avg_home_goals_conceded_last_5    10
avg_home_points_last_5            10
avg_away_goals_scored_last_5      13
avg_away_goals_conceded_last_5    13
avg_away_points_last_5            13
dtype: int64